name: Release

on:
  workflow_dispatch

jobs:
  release:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3
      - name: List Xcode installations
        run: sudo ls -1 /Applications | grep "Xcode"
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build executable for release
        run: swift build -c release --arch arm64 --arch x86_64 --product raise3d
      - name: Compress archive
        run: tar -czf ${{ github.ref_name }}.tar.gz -C .build/apple/Products/Release chatty
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.ref_name }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: mislav/bump-homebrew-formula-action@v2
        with:
          formula-name: raise3d-tool
          homebrew-tap: jetforme/homebrew-tap
          base-branch: main
          download-url: https://github.com/JetForMe/raise3d-swift/releases/download/${{ github.ref_name }}/${{ github.ref_name }}.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.CHATTY_COMMITTER_TOKEN }}
